# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazy-pulumi" do
  name "lazy-pulumi"
  desc "A stylish TUI for Pulumi Cloud, ESC, and NEO"
  homepage "https://github.com/dirien/lazy-pulumi"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazy-pulumi"

  on_macos do
    on_intel do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v#{version}/lazy-pulumi_#{version}_darwin_amd64.tar.gz"
      sha256 "1d6dcac761856be382f1705e9037f702497936456f5a7a2a03421a8b8710a74f"
    end
    on_arm do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v#{version}/lazy-pulumi_#{version}_darwin_arm64.tar.gz"
      sha256 "02ef802a336a15b066a19d5b9f31c4cf9f0116a7d2f9d3d432cf048b03d41b0e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v#{version}/lazy-pulumi_#{version}_linux_amd64.tar.gz"
      sha256 "00a7e46589a062f09f41d3627b499370277a9fe8653193ce279741a3cfdebbf1"
    end
    on_arm do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v#{version}/lazy-pulumi_#{version}_linux_arm64.tar.gz"
      sha256 "4ab316034ff39353b548471775b95ce19f838ea330ba3a29f1ada3f8255b85ab"
    end
  end

  # No zap stanza required
end
