# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazy-pulumi" do
  desc "A stylish TUI for Pulumi Cloud, ESC, and NEO"
  homepage "https://github.com/dirien/lazy-pulumi"
  version "0.9.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazy-pulumi"

  on_macos do
    on_intel do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.9.2/lazy-pulumi_0.9.2_darwin_amd64.tar.gz"
      sha256 "7815e00299c395cada73f854c38f0869e625a3016e327ef49aae88c40f3b2841"
    end
    on_arm do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.9.2/lazy-pulumi_0.9.2_darwin_arm64.tar.gz"
      sha256 "03b16800b763e95b2010ec9d1b2efcf30675a17ce443b929e9ba93e74c004d37"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.9.2/lazy-pulumi_0.9.2_linux_amd64.tar.gz"
      sha256 "0d08461a83837483970fdc5a8ae435159991e36ffa9e50b1a508b77c5cc675b1"
    end
    on_arm do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.9.2/lazy-pulumi_0.9.2_linux_arm64.tar.gz"
      sha256 "024e978f45c17af70e4330606b0873f7de1cd9fa1fa8ffc01f0ba49d68661cea"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazy-pulumi"]
    end
  end

  # No zap stanza required
end
