# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazy-pulumi" do
  desc "A stylish TUI for Pulumi Cloud, ESC, and NEO"
  homepage "https://github.com/dirien/lazy-pulumi"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazy-pulumi"

  on_macos do
    on_intel do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.9.0/lazy-pulumi_0.9.0_darwin_amd64.tar.gz"
      sha256 "ccba48f68c8e7722423bd6de041a7b3164e10cb9307b9d84d59a57e6f8a2abc0"
    end
    on_arm do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.9.0/lazy-pulumi_0.9.0_darwin_arm64.tar.gz"
      sha256 "2637c8d511e12131d77ab278758435a1355bb7f54469f0fc73ab36606c194c29"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.9.0/lazy-pulumi_0.9.0_linux_amd64.tar.gz"
      sha256 "004a38c96b512b62029e7d227d4a91f518aa7a444b1fc16e9ba2e3c7a4f8231f"
    end
    on_arm do
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.9.0/lazy-pulumi_0.9.0_linux_arm64.tar.gz"
      sha256 "27c67386deb8785a10e34efda60047fc8c3c7fdff9a7b98040780e452285e7fc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazy-pulumi"]
    end
  end

  # No zap stanza required
end
