# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3sair < Formula
  desc "K3SAIR 🏴‍☠️️ ('Corsair') is a cli for the installation of k3s in an Air-Gapped environment."
  homepage "https://github.com/dirien/k3sair-cli"
  version "0.5.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/k3sair-cli/releases/download/0.5.0/k3sair_0.5.0_darwin_amd64.tar.gz"
      sha256 "2b08502533037c424f7e952bac88cdd2ee5af651618460c9f20d9878eee6e595"

      def install
        bin.install "k3sair"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirien/k3sair-cli/releases/download/0.5.0/k3sair_0.5.0_darwin_arm64.tar.gz"
      sha256 "c4a18241d25642808a7c74c02591fadae58f286eee19f923c6bcae65a67b5538"

      def install
        bin.install "k3sair"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/k3sair-cli/releases/download/0.5.0/k3sair_0.5.0_linux_arm64.tar.gz"
      sha256 "d7af547b004485966da64d3e52dbe8ed948bf5882bd42949155b558f4b0e9cd3"

      def install
        bin.install "k3sair"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dirien/k3sair-cli/releases/download/0.5.0/k3sair_0.5.0_linux_amd64.tar.gz"
      sha256 "1a370a45092eb9bb2a35685c49c4948001affe31a8b099ba2cf9107c9385e705"

      def install
        bin.install "k3sair"
      end
    end
  end
end
