# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyPulumi < Formula
  desc "A stylish TUI for Pulumi Cloud, ESC, and NEO"
  homepage "https://github.com/dirien/lazy-pulumi"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.7.0/lazy-pulumi_0.7.0_darwin_amd64.tar.gz"
      sha256 "ff2d858fa548129ab0985898d7568d8269654f8bedaea8c95d575aed34b4f0a2"

      def install
        bin.install "lazy-pulumi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.7.0/lazy-pulumi_0.7.0_darwin_arm64.tar.gz"
      sha256 "e15a5767befb2ad83022ab3d90ed7da8fe9822a81ddb095a24e0ff94ea3040a0"

      def install
        bin.install "lazy-pulumi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.7.0/lazy-pulumi_0.7.0_linux_amd64.tar.gz"
      sha256 "565241c3e0dc754f88182680ebbeb0293485ba0355213c7d30bd9d5007b0fd18"
      def install
        bin.install "lazy-pulumi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.7.0/lazy-pulumi_0.7.0_linux_arm64.tar.gz"
      sha256 "48fe5be4a1759963cc5c8b25ab3f0f4dbb442501b8dc5fd6572fffce47e090a9"
      def install
        bin.install "lazy-pulumi"
      end
    end
  end
end
