# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyPulumi < Formula
  desc "A stylish TUI for Pulumi Cloud, ESC, and NEO"
  homepage "https://github.com/dirien/lazy-pulumi"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.5.0/lazy-pulumi_0.5.0_darwin_amd64.tar.gz"
      sha256 "4dd6962a330c0d7cff63cfc4bd2fa06be6970ae360b1b29a1036ca7de52d8a13"

      def install
        bin.install "lazy-pulumi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.5.0/lazy-pulumi_0.5.0_darwin_arm64.tar.gz"
      sha256 "f6f3455cb4be4d4dbdd291ec420158a246d97252f450d5b6851c91ea60987e0d"

      def install
        bin.install "lazy-pulumi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.5.0/lazy-pulumi_0.5.0_linux_amd64.tar.gz"
      sha256 "94c6d830feb5b248cdaa1bf7bcedb97b47f8e992cf3079e8fe7a7ea88f02af5f"
      def install
        bin.install "lazy-pulumi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.5.0/lazy-pulumi_0.5.0_linux_arm64.tar.gz"
      sha256 "1f75aa679056a5bbcd17b1a1f2813616f3b825b125f34cb7ad9b2b4e6276c738"
      def install
        bin.install "lazy-pulumi"
      end
    end
  end
end
