# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyPulumi < Formula
  desc "A stylish TUI for Pulumi Cloud, ESC, and NEO"
  homepage "https://github.com/dirien/lazy-pulumi"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.6.1/lazy-pulumi_0.6.1_darwin_amd64.tar.gz"
      sha256 "d5690d48f96b64473338fc6c43060daffb6457200c8a37de62f8da5e36da7fb3"

      def install
        bin.install "lazy-pulumi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.6.1/lazy-pulumi_0.6.1_darwin_arm64.tar.gz"
      sha256 "3e9024731f49bc8c7a61b50c541340e494ae22ce03f5433831f59669d543e612"

      def install
        bin.install "lazy-pulumi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.6.1/lazy-pulumi_0.6.1_linux_amd64.tar.gz"
      sha256 "9ca942d967956adfe4cebe7b91022c985a07b24c148fd6e9c368b991861c7606"
      def install
        bin.install "lazy-pulumi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/lazy-pulumi/releases/download/v0.6.1/lazy-pulumi_0.6.1_linux_arm64.tar.gz"
      sha256 "7b7e971f1b3c94c9efeddb74998ae4c181c22295d3ce84b56198950779395099"
      def install
        bin.install "lazy-pulumi"
      end
    end
  end
end
