# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minectl < Formula
  desc "minectl️️ 🗺️ is a cli for creating Minecraft (java or bedrock) server on different cloud provider."
  homepage "https://github.com/dirien/minectl"
  version "0.31.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dirien/minectl/releases/download/v0.31.0/minectl_0.31.0_darwin_arm64.tar.gz"
      sha256 "d82bb778a350c762e66c2e5d756ddf8465829b383c31a304affff86cac718634"

      def install
        bin.install "minectl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dirien/minectl/releases/download/v0.31.0/minectl_0.31.0_darwin_amd64.tar.gz"
      sha256 "9f1665704666f5f4ac9f5cc7a6661d6dc675ca9aadb610e070645f223d191518"

      def install
        bin.install "minectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/minectl/releases/download/v0.31.0/minectl_0.31.0_linux_arm64.tar.gz"
      sha256 "5d9876a12bc5bb5f9b89af5a7e83e120de4b9a277af86b40b8377545b31b2529"

      def install
        bin.install "minectl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dirien/minectl/releases/download/v0.31.0/minectl_0.31.0_linux_amd64.tar.gz"
      sha256 "8013ced0513fdfd075cd461440d1da5c64fd0b88ddc911e15caf61ba18987b56"

      def install
        bin.install "minectl"
      end
    end
  end
end
