# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minectl < Formula
  desc "minectl️️ 🗺️ is a cli for creating Minecraft (java or bedrock) server on different cloud provider."
  homepage "https://github.com/dirien/minectl"
  version "0.6.1"
  license "Apache License 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/minectl/releases/download/v0.6.1/minectl_0.6.1_darwin_amd64.tar.gz"
      sha256 "3a4a2ca51d92dee69bb6d98037e7ef30136d812a4b0db6176eeec5d861e1b231"
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirien/minectl/releases/download/v0.6.1/minectl_0.6.1_darwin_arm64.tar.gz"
      sha256 "c944c5caff27a0a653b7c07adc8e914340eedb3558e25d8ffe5a8bbd9eafad11"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/minectl/releases/download/v0.6.1/minectl_0.6.1_linux_amd64.tar.gz"
      sha256 "6f56d8ed26c2faa32df92f65436ab07f67763b6b0cba3664d20f14d9e19a0a1d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/minectl/releases/download/v0.6.1/minectl_0.6.1_linux_arm64.tar.gz"
      sha256 "c84478c6f02362018c70472d6b523c198956a817ca5259ac72963e14ee4deebc"
    end
  end

  def install
    bin.install "minectl"
  end
end
