# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PulumiCcstatusline < Formula
  desc "Pulumi stack info in your Claude Code status line"
  homepage "https://github.com/dirien/pulumi-ccstatusline"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/pulumi-ccstatusline/releases/download/v0.1.0/pulumi-ccstatusline_0.1.0_darwin_amd64.tar.gz"
      sha256 "8b948dcd3f504d3768d0903b8fadfb5fb172cfc2c4fda6f00fbc416082e44614"

      def install
        bin.install "pulumi-ccstatusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirien/pulumi-ccstatusline/releases/download/v0.1.0/pulumi-ccstatusline_0.1.0_darwin_arm64.tar.gz"
      sha256 "c5a64cf85387f714c6574ae405e9a825d0a4751dfd04370d541545587ea7b116"

      def install
        bin.install "pulumi-ccstatusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/pulumi-ccstatusline/releases/download/v0.1.0/pulumi-ccstatusline_0.1.0_linux_amd64.tar.gz"
      sha256 "22591076cefd50adea41e45372dbda862f64dc2493f19a234cc39cdf40c1db36"
      def install
        bin.install "pulumi-ccstatusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/pulumi-ccstatusline/releases/download/v0.1.0/pulumi-ccstatusline_0.1.0_linux_arm64.tar.gz"
      sha256 "9aef57eb773a6c5e9520f1c1ea341c5658da9ecc17948253178cccd97a44cc04"
      def install
        bin.install "pulumi-ccstatusline"
      end
    end
  end
end
