# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfu < Formula
  desc "tfu is a Terraform helper to update the providers."
  homepage "https://github.com/dirien/tfu"
  version "0.4.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dirien/tfu/releases/download/v0.4.0/tfu_0.4.0_darwin_arm64.tar.gz"
      sha256 "e615c0fbb44c2ca3d0ba5dfcee019419e7a9a908d72b4a9d616f506271aafc37"

      def install
        bin.install "tfu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dirien/tfu/releases/download/v0.4.0/tfu_0.4.0_darwin_amd64.tar.gz"
      sha256 "2dd379ba972185e22b637e240c56b403ca541ad446e4fc9d4d9e08efee7b46c6"

      def install
        bin.install "tfu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/tfu/releases/download/v0.4.0/tfu_0.4.0_linux_arm64.tar.gz"
      sha256 "12dbf458ec4fb061e8ec134a438bcb2c4e11ebf255b13a49af8f03565b97b888"

      def install
        bin.install "tfu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dirien/tfu/releases/download/v0.4.0/tfu_0.4.0_linux_amd64.tar.gz"
      sha256 "29744e1a0277b0f15d6b15b2f934ac52cf622f6f3c1a30a59bbbcfda865a9130"

      def install
        bin.install "tfu"
      end
    end
  end
end
