# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfu < Formula
  desc "tfu is a Terraform helper to update the providers."
  homepage "https://github.com/dirien/tfu"
  version "0.1.0"
  license "Apache License 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/tfu/releases/download/v0.1.0/tfu_0.1.0_darwin_amd64.tar.gz"
      sha256 "c91f381c3172a1458cc96b59bfb112fa5dc725aac51202fabbc7b591f787d523"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dirien/tfu/releases/download/v0.1.0/tfu_0.1.0_linux_amd64.tar.gz"
      sha256 "fe019febee8ea3109b29fbd77167e3bb9a1704e1c4d8ccf3804079aaa44af3bd"
    end
  end

  def install
    bin.install "tfu"
  end
end
